SOURCE := main.cpp Animal.cpp Dog.cpp Cat.cpp

NAME := polymorphism

all: $(NAME)

$(NAME): $(SOURCE)
	c++ -Wall -Wextra -Werror -std=c++98 $(SOURCE) -o $(NAME)

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
